# Generated by Django 4.1.5 on 2023-01-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traveling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, default='', max_length=255)),
                ('Last_name', models.CharField(blank=True, default='', max_length=255)),
                ('Email', models.CharField(blank=True, default='', max_length=255)),
                ('Phone_Number', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
