# Generated by Django 2.2.5 on 2023-01-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Traveling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveling',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
